export const MeasurementParameter = {
  // Antropometri
  BODY_WEIGHT: "BODY_WEIGHT",
  HEIGHT: "HEIGHT",
  BMI: "BMI",
  BODY_TEMPERATURE: "BODY_TEMPERATURE",

  // Tekanan Darah
  BLOOD_PRESSURE_SYSTOLIC: "BLOOD_PRESSURE_SYSTOLIC",
  BLOOD_PRESSURE_DIASTOLIC: "BLOOD_PRESSURE_DIASTOLIC",
  BLOOD_PRESSURE_MEAN: "BLOOD_PRESSURE_MEAN",

  // Jantung & Sirkulasi
  HEART_RATE: "HEART_RATE",
  FETAL_HEART_RATE: "FETAL_HEART_RATE",
  PULSE_RATE: "PULSE_RATE",

  // Respirasi & Oksigen
  RESPIRATORY_RATE: "RESPIRATORY_RATE",
  SPO2: "SPO2",

  // Komposisi Tubuh
  BODY_FAT_PERCENTAGE: "BODY_FAT_PERCENTAGE",
  MUSCLE_MASS: "MUSCLE_MASS",
  VISCERAL_FAT: "VISCERAL_FAT",
  BONE_MASS: "BONE_MASS",
  BODY_WATER_PERCENTAGE: "BODY_WATER_PERCENTAGE",
  BASAL_METABOLIC_RATE: "BASAL_METABOLIC_RATE",
  PROTEIN_PERCENTAGE: "PROTEIN_PERCENTAGE",
  LEAN_BODY_MASS: "LEAN_BODY_MASS",
  BODY_AGE: "BODY_AGE",
  OBESITY_LEVEL: "OBESITY_LEVEL",

  // Elektrofisiologi
  ECG: "ECG",
  PLETHYSMOGRAM: "PLETHYSMOGRAM",

  // Central Monitoring
  PATIENT_MONITOR: "PATIENT_MONITOR",
  VITAL_SIGN_MONITOR: "VITAL_SIGN_MONITOR",

  // Lainnya
  OTHER: "OTHER",
} as const;

export type MeasurementParameter = keyof typeof MeasurementParameter;
